// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {swails} from '../models';
import {snake} from '../models';
import {context} from '../models';

export function Commands():Promise<Array<swails.WailsCommand>>;

export function CurrentInput(arg1:swails.SWails,arg2:snake.Input):Promise<swails.WailsInput>;

export function Decorate(arg1:context.Context,arg2:swails.SWails,arg3:snake.Snake,arg4:Array<snake.Input>,arg5:Array<snake.Middleware>):Promise<void>;

export function Events():Promise<Array<swails.WailsEvent>>;

export function Inputs():Promise<Array<swails.WailsInput>>;

export function InputsFor(arg1:swails.WailsCommand):Promise<Array<swails.WailsInput>>;

export function ManagedResolvers(arg1:context.Context):Promise<Array<snake.Resolver>>;

export function OnSnakeInit(arg1:context.Context,arg2:snake.Snake):Promise<void>;

export function OptionsForEnum(arg1:swails.WailsInput):Promise<Array<string>>;

export function ProvideContextResolver():Promise<snake.Resolver>;

export function ResolveEnum(arg1:string,arg2:Array<string>):Promise<string>;

export function Run(arg1:swails.WailsCommand):Promise<swails.WailsHTMLResponse>;

export function RunWithWriter(arg1:string,arg2:swails.WailsCommand):Promise<swails.WailsWriter>;

export function SetLifecycleContext(arg1:context.Context):Promise<void>;

export function UpdateInput(arg1:swails.WailsInput):Promise<swails.WailsInput>;
