// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Commands() {
  return window['go']['swails']['WailsSnake']['Commands']();
}

export function CurrentInput(arg1) {
  return window['go']['swails']['WailsSnake']['CurrentInput'](arg1);
}

export function Decorate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['swails']['WailsSnake']['Decorate'](arg1, arg2, arg3, arg4, arg5);
}

export function Inputs() {
  return window['go']['swails']['WailsSnake']['Inputs']();
}

export function InputsFor(arg1) {
  return window['go']['swails']['WailsSnake']['InputsFor'](arg1);
}

export function ManagedResolvers(arg1) {
  return window['go']['swails']['WailsSnake']['ManagedResolvers'](arg1);
}

export function OnSnakeInit(arg1, arg2) {
  return window['go']['swails']['WailsSnake']['OnSnakeInit'](arg1, arg2);
}

export function OptionsForEnum(arg1) {
  return window['go']['swails']['WailsSnake']['OptionsForEnum'](arg1);
}

export function ProvideContextResolver() {
  return window['go']['swails']['WailsSnake']['ProvideContextResolver']();
}

export function ResolveEnum(arg1, arg2) {
  return window['go']['swails']['WailsSnake']['ResolveEnum'](arg1, arg2);
}

export function Run(arg1) {
  return window['go']['swails']['WailsSnake']['Run'](arg1);
}

export function UpdateInput(arg1) {
  return window['go']['swails']['WailsSnake']['UpdateInput'](arg1);
}
