name: simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
  workflow_dispatch:
jobs:
  simver:
    uses: walteh/simver/.github/workflows/simver.yaml@v0.6.0
    secrets: inherit
